export const Modal: string;
export const ModalInner: string;
export const ModalMedium: string;
export const ModalLarge: string;
export const ModalSmall: string;
export const ModalFooter: string;
export const ModalButtons: string;
export const OkBtn: string;
export const CancelBtn: string;
