export const ClientInfoFormSubmitStatus: string;
export const ClientInfoForm: string;
export const ClientInfoFormSection: string;
export const ClientInfoFormInputContainer: string;
export const ClientInfoFormSubmitSection: string;
export const ClientFormGroup: string;
export const ClientFormInputContainer: string;
export const ClientViewLabel: string;
export const ClientViewValue: string;
