export const MaterialFormContainer: string;
export const MaterialColumn: string;
export const QtyColumn: string;
export const UnitsColumn: string;
export const SupplierColumn: string;
export const ProfitColumn: string;
export const CostColumn: string;
export const TotalColumn: string;
export const ButtonColumn: string;
