export const TabIndicatorTitle: string;
export const TabIndicatorTitleActive: string;
export const TabIndicator: string;
export const TabIndicatorCount: string;
export const TabIndicatorCountDefault: string;
export const TabIndicatorCountPrimary: string;
export const TabIndicatorCountSecondary: string;
export const TabIndicatorCountImportant: string;
export const TabIndicatorCountActive: string;
